# Generated by Django 6.0.2 on 2026-03-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(max_length=500)),
                ('target_keyword', models.CharField(blank=True, max_length=200)),
                ('audit_data', models.JSONField(blank=True, default=dict)),
                ('audit_report', models.TextField(blank=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Audit',
                'verbose_name_plural': 'Website Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
