# Generated by Django 6.0.2 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_websiteaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteaudit',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websiteaudit',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='websiteaudit',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@brandmeup.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Omni Path Marketing', max_length=200),
        ),
        migrations.AlterField(
            model_name='websiteaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verification_sent', 'Verification Sent'), ('email_verified', 'Email Verified'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
