# Generated by Django 6.0.2 on 2026-04-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_websiteaudit_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('analytics', 'Google Analytics'), ('search_console', 'Google Search Console'), ('gbp', 'Google Business Profile')], max_length=30)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('property_id', models.CharField(blank=True, help_text='GA4 Property ID or Search Console site URL', max_length=200)),
                ('is_connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.client')),
            ],
            options={
                'verbose_name': 'Client Connection',
                'verbose_name_plural': 'Client Connections',
                'ordering': ['-updated_at'],
                'unique_together': {('client', 'service')},
            },
        ),
    ]
