# Generated by Django 6.0.2 on 2026-04-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_clientconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnection',
            name='service',
            field=models.CharField(choices=[('analytics', 'Google Analytics'), ('search_console', 'Google Search Console'), ('gbp', 'Google Business Profile'), ('meta_facebook', 'Meta Facebook'), ('meta_instagram', 'Meta Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X')], max_length=30),
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media_urls', models.JSONField(blank=True, default=list, help_text='List of media URLs (images, videos)')),
                ('link_url', models.URLField(blank=True, help_text='URL to include in post')),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='When to publish. Null if draft.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='core.client')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, help_text='Post ID returned by the platform API after publishing', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_posts', to='core.scheduledpost')),
            ],
            options={
                'ordering': ['platform'],
                'unique_together': {('post', 'platform')},
            },
        ),
    ]
