# Generated by Django 6.0.2 on 2026-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_init_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnection',
            name='service',
            field=models.CharField(choices=[('analytics', 'Google Analytics'), ('search_console', 'Google Search Console'), ('gbp', 'Google Business Profile'), ('meta_facebook', 'Meta Facebook'), ('meta_instagram', 'Meta Instagram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scheduledplatform',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest')], max_length=20),
        ),
    ]
